version: '3.8'

services:
  postgres-reservas:
    image: postgres:15
    container_name: postgres-reservas
    restart: always
    environment:
      POSTGRES_DB: reservasdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"

  reservas-service:
    build: ./reservas-service
    container_name: reservas-service
    restart: always
    depends_on:
      - postgres-reservas
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-reservas:5432/reservasdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8081"

  postgres-usuarios:
    image: postgres:15
    container_name: postgres-usuarios
    restart: always
    environment:
      POSTGRES_DB: usuariosdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"

  usuarios-service:
    build: ./usuarios-service
    container_name: usuarios-service
    restart: always
    depends_on:
      - postgres-usuarios
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-usuarios:5432/usuariosdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8082:8082"
